// src/app/layout.tsx
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";

// IMPORTING FONT FROM GOOGLE FONTS (Giving Medieval vibes)
import { Cinzel, EB_Garamond } from "next/font/google";

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "700"], // Choose weights as needed
});
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400"], // or adjust as needed
});

export const metadata = {
  title: "AI Storyteller",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${cinzel.className}, ${ebGaramond.className}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
